### ISSUE TITLE
Docs for `__init__.py` files

### ISSUE THREAD

**Issue by gcalcedo** [gcalcedo/clusview#70]
`__init__.py` files in the root of each `clusview` module lack a concise explanation of the package contents.

A docstring should be implemented for each one of the form:
```python
"""
Concise package explanation.
"""
```

**Comment by somak-chatterjee** [comment]
Do you have any requirements for what you need to cover for the explanation?

**Comment by gcalcedo** [comment]
> Do you have any requirements for what you need to cover for the explanation?

These docstrings will be displayed on the tooltip of the module imports. So, I'm looking for a short description. No more than 4 or 5 short sentences at most.

Some `__init.py__` files, like the one for the `loaders` package, already have a docstring (although these might benefit from some improvements too). They are displayed like this:

<img width="587" alt="Screenshot 2024-06-14 at 23 20 01" src="https://github.com/gcalcedo/clusview/assets/49457798/12492575-d32b-4063-99f4-22412d2112ed">

I'll assign you to the issue then. Thank you!

**Comment by somak-chatterjee** [comment]
Alright. I'll take a look at the `loaders` package and try to implement it for the other `__init.py__` files.
